# Generated by Django 2.2 on 2019-04-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190413_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='profile',
        ),
        migrations.AddField(
            model_name='skill',
            name='profile',
            field=models.ManyToManyField(related_name='skills', to='core.Profile'),
        ),
    ]
