# Generated by Django 2.2 on 2019-04-14 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_auto_20190414_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position_Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(max_length=1)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
