# Generated by Django 2.2 on 2019-04-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_position_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position_application',
            name='status',
            field=models.IntegerField(),
        ),
    ]
