# Generated by Django 2.2 on 2019-04-20 02:52

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_position_application_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
