# Generated by Django 2.2 on 2019-04-20 03:05

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190420_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
