# Generated by Django 2.2 on 2019-04-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190420_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='availability',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
