# Generated by Django 2.2 on 2019-04-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_position_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='other_skills',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
