# Generated by Django 2.2 on 2019-05-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_profile_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position_application',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
