# Generated by Django 2.2 on 2019-05-19 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190501_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='title',
        ),
    ]
