# Generated by Django 2.2 on 2019-05-19 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_position_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='title',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.Skill'),
            preserve_default=False,
        ),
    ]
