# Generated by Django 2.2 on 2019-05-19 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_position_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.Skill'),
        ),
    ]
