# Generated by Django 2.2 on 2019-05-19 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20190519_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Skill'),
        ),
    ]
