# Generated by Django 2.2 on 2019-05-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20190519_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='title_position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
