# Generated by Django 2.2 on 2019-05-20 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20190519_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.Skill'),
            preserve_default=False,
        ),
    ]
